config/routes.rb
Spree::Core::Engine.routes.prepend do
  namespace :admin do
    resources :campaigns
  end
end

app/models/spree/campaign.rb
if RUBY_VERSION < '1.9'
  require 'fastercsv'
  CSV = FasterCSV
else
  require 'csv'
end

# Note: This could/should somehow integrate with Spree's own PromotionRule/PromotionAction system.
module Spree
  class Campaign < ActiveRecord::Base
    has_many :promotions

    with_options(:if => :period_mode_days?) do |v|
      v.validates :days, :numericality => { :only_integer => true, :greater_than => 0, :allow_blank => true }
      v.validates_presence_of :starts_at, :message => 'must be given if period mode is "days"'
    end

    after_create :create_promotions
    after_update :update_promotions

    before_validation :calculate_ends_at_for_days

    def coupons_available
      # OPTIMIZE: At least the inner sub query could probably be rewritten with a JOIN.
      conditions = <<-sql
        usage_limit IS NULL OR
        usage_limit > (
          SELECT COUNT(*) FROM #{Spree::Adjustment.table_name} sa
	        WHERE sa.originator_type = 'Spree::PromotionAction' AND sa.originator_id IN (
	          SELECT id FROM #{Spree::PromotionAction.table_name} spa WHERE spa.activator_id = #{Spree::Promotion.table_name}.id
	        )
        )
      sql
      promotions.where(conditions).count
    end

    def coupons_total
      promotions.count
    end

    def to_csv
      CSV.generate(:col_sep => ';', :headers => true, :force_quotes => true) do |csv|
        # header row
        csv << ['Campaign', 'Code', 'Used?']
        # data rows
        promotions.each do |promotion|
          csv << [name, promotion.code, promotion.usage_limit_exceeded? ? 'Yes' : 'No']
        end
      end
    end

  private

    def period_mode_days?; period_mode == 'days'; end
    def period_mode_fixed_date?; period_mode == 'fixed_date'; end

    def calculate_ends_at_for_days
      return unless period_mode_days? && days.present? && starts_at.present?
      self.ends_at = starts_at + (days.to_i).days
    end

    def create_promotions
      number_of_coupons.to_i.times do |i|
        promotion = promotions.create!(
          :name => "#{name} ##{i + 1}",
          :usage_limit => 1,
          :event_name => 'spree.checkout.coupon_code_added',
          :code => Devise.friendly_token.first(10).upcase,
          :starts_at => starts_at,
          :expires_at => ends_at,
        )
        Spree::Promotion::Actions::CreateAdjustment.create! do |action|
          action.promotion = promotion
          action.calculator = Spree::Calculator::FlatRate.new(:preferred_amount => value)
        end
      end
    end

    def update_promotions
      promotions.update_all(:starts_at => starts_at, :expires_at => ends_at)
    end

  end
end

app/controllers/spree/admin/campaigns_controller.rb
module Spree
  module Admin
    class CampaignsController < ResourceController
      respond_to :csv, :only => :show

      def show
        campaign = @object

        send_data(
          campaign.to_csv,
          :type        => "text/csv; charset=utf-8; header=present",
          :disposition => "attachment; filename=#{campaign.name}.csv"
        )
      end

    protected

      def build_resource
        @campaign = Campaign.new(params[:campaign])
      end
    end
  end
end

app/views/spree/admin/campaigns/_form.html.erb
<%= render 'spree/shared/error_messages', :target => @campaign %>

<fieldset id="general_fields">
  <p>Note: Name, number of coupons and value cannot be changed after a campaign has been created.</p>

  <%- options = { :disabled => !@campaign.new_record? } -%>
  <legend><%= t(:general) %></legend>
  <%= f.field_container(:name) do %>
    <%= f.label :name %><br />
    <%= f.text_field :name, options %>
  <% end %>
  <%= f.field_container(:number_of_coupons) do %>
    <%= f.label :number_of_coupons %><br />
    <%= f.text_field :number_of_coupons, options %>
  <% end %>
  <%= f.field_container(:value) do %>
    <%= f.label :value %><br />
    <%= f.text_field :value, options %>
  <% end %>

  <%- date_format = '%Y/%m/%d' # would love to use I18n.t(:format, :scope => 'spree.date_picker', :default => 'yy/mm/dd'), but it only works for JS -%>
  <legend><%= t(:campaign_period) %></legend>
  <%= f.field_container(:starts_at) do %>
    <%= f.label :starts_at %><br />
    <%= f.text_field :starts_at, :class => 'datepicker', :value => @campaign.starts_at.present? ? @campaign.starts_at.strftime(date_format) : nil %>
  <% end %>

  <%= f.field_container(:period_mode) do %>
    <%= f.label :period_mode %>

    <label>
      <%= f.radio_button :period_mode, 'days' %> days
    </label>

    <label>
      <%= f.radio_button :period_mode, 'fixed_date' %> fixed date
    </label>
  <%- end -%>

  <div id="fields_for_days" class="fields_for_period_mode" style="display:none;">
    <%= f.field_container(:days) do %>
      <%= f.label :days %><br />
      <%= f.text_field :days %>
    <% end %>
  </div>
  <div id="fields_for_fixed_date" class="fields_for_period_mode" style="display:none;">
    <%= f.field_container(:ends_at) do %>
      <%= f.label :ends_at %><br />
      <%= f.text_field :ends_at, :class => 'datepicker', :value => @campaign.ends_at.present? ? @campaign.ends_at.strftime(date_format) : nil %>
    <% end %>
  </div>
</fieldset>

<%= javascript_tag do %>
  jQuery(function($) {
    var campaignPeriodModeFieldSelector = "input[name='campaign[period_mode]']";

    var toggleFieldsForSelectedPeriodMode = function() {
      var selectedPeriodMode = $(campaignPeriodModeFieldSelector + ':checked').val();
      $('.fields_for_period_mode').hide();
      $('#fields_for_' + selectedPeriodMode).show();
    };
    toggleFieldsForSelectedPeriodMode(); // toggle fields for selected mode on page load

    $(campaignPeriodModeFieldSelector).on('change', toggleFieldsForSelectedPeriodMode); // ... and when the radio buttons are changed
  });
<% end %>

app/views/spree/admin/campaigns/edit.html.erb
<h1><%= t(:edit_campaign) %></h1>

<%= form_for(:campaign, :url => object_url, :method => :put) do |f| %>
  <%= render 'form', :f => f %>
  <%= render 'spree/admin/shared/edit_resource_links' %>
<% end %>

app/views/spree/admin/campaigns/index.html.erb
<div class="toolbar">
  <ul class="actions">
    <li>
      <%= button_link_to t(:new_campaign), spree.new_admin_campaign_path, :icon => 'add' %>
    </li>
  </ul>
  <br class="clear" />
</div>

<h1><%= t(:campaigns) %></h1>

<table class="index">
  <thead>
    <tr>
      <th><%= t(:name) %></th>
      <th><%= t(:value) %></th>
      <th><%= t(:number_of_coupons) %></th>
      <th><%= t(:usage) %></th>
      <th><%= t(:campaign_period) %></th>
      <th style="width:190px;"><%= t(:action) %></th>
    </tr>
  </thead>
  <tbody>
    <%- @campaigns.each do |campaign| -%>
      <tr id="<%= spree_dom_id(campaign) %>">
        <td><%= campaign.name %></td>
        <td><%= money(campaign.value) %></td>
        <td><%= campaign.number_of_coupons %></td>
        <td><%= campaign.coupons_available %> / <%= campaign.coupons_total %> available</td>
        <td>
          Start: <%= campaign.starts_at.present? ? l(campaign.starts_at, :format => :short) : 'n/a' %>,
          End: <%= campaign.ends_at.present? ? l(campaign.ends_at, :format => :short) : 'n/a' %>
        </td>
        <td>
          <%= link_to 'Download CSV', admin_campaign_path(campaign, :csv) %>&nbsp;
          <%= link_to_edit(campaign) %>&nbsp;
          <%= link_to_delete(campaign) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/campaigns/new.html.erb
<h1><%= t(:new_campaign) %></h1>

<%= form_for(:campaign, :url => collection_url) do |f| %>
  <%= render 'form', :f => f %>
  <%= render 'spree/admin/shared/new_resource_links' %>
<% end %>